@startuml

!$platform = %getenv("PLATFORM_NAME")
!$export_lang = %getenv("export_lang")

title Login Flow

[*] --> Prompt

Prompt --> Authenticate
Prompt -> ForgotPass
Prompt --> CreateAccount
Prompt --> Prompt
Prompt: String?

state CreateAccount {
    [*] --> EnterInfo
    EnterInfo --> Submit
    Submit --> EnterInfo
    EnterInfo: String?
    Submit: User
    Submit --> [*]: Credentials
}
CreateAccount --> Prompt
CreateAccount --> Authenticate
CreateAccount: String?

Authenticate --> Prompt
Authenticate: Credentials

ForgotPass -> Prompt
ForgotPass: String

note "This is a note $platform $export_lang about login " as N1

note left of Prompt
    This is where the
    login screen goes
end note

Authenticate --> [*]: OAuthToken
@enduml

@startuml
enum LoginViewResult {
    login: Credentials
    register
    forgotPassword: String
}

class User {
    {field} +userId: UUID = UUID.randomUUID()
    +firstName: String
    +lastName: String
    +email: String
    +password: String
}

class OAuthToken {
    + token: String
    + type: String
    + expiration: Date
}

class Credentials {
    + username: String
    + password: String
}
@enduml
