@startuml

!$platform = %getenv("PLATFORM_NAME")
!$export_lang = %getenv("export_lang")

title Login Flow

[*] --> Prompt

Prompt --> Authenticate
Prompt -> ForgotPass
Prompt --> CreateAccount
Prompt --> Prompt
Prompt: String?

state CreateAccount {
    [*] --> EnterInfo
    EnterInfo --> Submit
    Submit --> EnterInfo
    EnterInfo: String?
    Submit: User
    Submit --> [*]: Credentials
}
CreateAccount --> Prompt
CreateAccount --> Authenticate
CreateAccount: String?

Authenticate --> Prompt
Authenticate: Credentials

ForgotPass -> Prompt
ForgotPass: String

note "This is a note $platform $export_lang about login " as N1

note left of Prompt
    This is where the
    login screen goes
end note

Authenticate --> [*]: OAuthToken
@enduml
